LIBSTREAM_DIR = libstream
TESTLIBSTREAM_DIR = testlibstream

all:
	cd $(LIBSTREAM_DIR) ; $(MAKE)
	cd $(TESTLIBSTREAM_DIR) ; $(MAKE)

clean:
	cd $(LIBSTREAM_DIR) ; $(MAKE) clean
	cd $(TESTLIBSTREAM_DIR) ; $(MAKE) clean

distclean: clean
